title: My Jekyll Site
description: A simple Jekyll site
url: https://logianwilliam.github.io/sillywilli
baseurl: "/sillywilli"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
